#FROM is generated dynamically by the Makefile

# link to proper devmapper library version
RUN ln -fs /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 /lib/x86_64-linux-gnu/libdevmapper.so.1.02

# increase the executor timeout to account for the potential delay in pulling a docker image to the slave
RUN echo '20mins' > /etc/mesos-slave/executor_registration_timeout

ENTRYPOINT ["/bin/sh", "-c"]

CMD /bin/slave

ADD slave /bin/slave

